Recursive find
FundingCircle/hellgrid pull request #14
Opened 2016-09-13 14:35 UTC by Arepo

Hi all,

This is a minor contribution to a) enable recursive searching in nested projects if the user wants it, and b) update the specs to use the much prettier Ruby 2.3 squiggly heredoc syntax. It does mean that the gem requires Ruby 2.3.1 to run (squiggly heredoc in 2.3.0 seems to be buggy).

Kind regards,

Sasha

2016-09-20 09:31 UTC, sgerrand commented
Requiring a particular version of Ruby just for HEREDOC syntax is a 👎  from me.

2016-09-20 09:32 UTC, sgerrand commented on spec/hellgrid/project_spec.rb
> +    create_file lockfile_path,  <<~FOO_GEMFILE
What material benefit do you get from using the `~` HEREDOC syntax?

2016-09-20 09:33 UTC, sgerrand commented on spec/hellgrid_spec.rb
> +  it 'searches recursively within folders if you flag it to' do
🙋  Should use a `context` block to isolate the `-r` flag, e.g.:
```ruby
context 'when passing -r` do
  it 'searches recursively within folders'
end
```

2016-09-20 09:34 UTC, sgerrand requested changes
Please remove the `~` HEREDOC format and the `required_ruby_version` constraint. These add an artificial constraint to consumers of this gem.

2016-10-17 22:55 UTC, Arepo commented on spec/hellgrid/project_spec.rb
> +    create_file lockfile_path,  <<~FOO_GEMFILE
I've removed this now.

2016-10-17 23:07 UTC, sgerrand approved these changes
LGTM. 👍

2016-10-17 23:07 UTC, merged

2016-10-17 23:08 UTC, sgerrand commented
Thanks for your contribution, @Arepo! 💝